# Generated by Django 5.2 on 2025-06-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_propertylisting_delete_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Liczba pokoi', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='surface',
            field=models.PositiveIntegerField(blank=True, help_text='Powierzchnia w m²', null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.district'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.transactiontype'),
        ),
    ]
